version: v1beta1
containers:
  - name: mongodb
    image: dockerfile/mongodb
    volumeMounts:
      - name: mongodb-data
        path: /data/db
    ports:
      - name: mongodb
        hostPort: 27017
        containerPort: 27017

volumes:
  - name: mongodb-data
    hostPath: /mnt/pd1/mongodb/data/db